// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class DoorsGPG
{
        public const string achievement_braaaaaaaaains_i_mean_dooooooooors = "CgkIso-F-qQIEAIQBw"; // <GPGSID>
        public const string achievement_you_really_dont_like_this_person = "CgkIso-F-qQIEAIQBA"; // <GPGSID>
        public const string leaderboard_best_scores = "CgkIso-F-qQIEAIQAA"; // <GPGSID>
        public const string achievement_could_you_close_it_any_faster = "CgkIso-F-qQIEAIQBg"; // <GPGSID>
        public const string achievement_well_i_have_to_admit_youre_getting_good = "CgkIso-F-qQIEAIQBQ"; // <GPGSID>
        public const string achievement_so_close_yet_not_closed_enough = "CgkIso-F-qQIEAIQAw"; // <GPGSID>

}

